version: '3'
services:
    database:
        image: "postgres"
        env_file:
            - database.env
        volumes:
            - database-data:/var/lib/postgresql/data/
    whirlpool:
        build:
            context: ./
            dockerfile: Dockerfile
        env_file: 
            - .env

volumes:
  database-data: